author: Stefan van den Oord
module: ReRxSwift
module_version: 2.2.2
podspec: ReRxSwift.podspec
github_url: https://github.com/svdo/ReRxSwift
github_file_prefix: https://github.com/svdo/ReRxSwift/tree/master
