sudo: false
language: swift
os: osx
osx_image: xcode10.2
before_install:
  - gem update --system
  - gem install bundler
cache:
  - bundler
  - cocoapods
before_script:
  - bundle exec pod repo update
script:
  - xcodebuild -workspace ReRxSwift.xcworkspace -scheme AllTests test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=11.2' | bundle exec xcpretty
  - bundle exec jazzy
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: docs
  on:
    branch: master
